name: Create Tag & Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create-tag-and-release:
    # Running only when PR is merged
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Extract version from setup.py
        id: version
        run: echo "VERSION=$(python setup.py --version)" >> "$GITHUB_OUTPUT"

      - name: Extract title of PR
        id: extract_pr_title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo the title of the PR is $TITLE
          echo "PR_TITLE=$TITLE" >> "$GITHUB_OUTPUT"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: ${{ steps.extract_pr_title.outputs.PR_TITLE }}
          body: auto-release
          draft: false
          prerelease: false
